spark.eventLog.enabled true
spark.eventLog.compress true
spark.eventLog.dir file:///tmp/spark-events
spark.history.fs.logDirectory file:///tmp/spark-events
spark.driver.bindAddress 0.0.0.0
spark.driver.host host.docker.internal
spark.driver.port 38000
spark.blockManager.port 38001
spark.pyspark.python /usr/bin/python3
spark.pyspark.driver.python /usr/local/bin/python
spark.ui.bindAddress 0.0.0.0
spark.ui.reverseProxy true
spark.ui.reverseProxyUrl http://localhost:8080
